### ISSUE TITLE
Liferaft status

### ISSUE THREAD

**Issue by garrensmith** [unshiftio/liferaft#13]
This library looks really cool and the documentation is excellent. Do you know if this code is being used in production anywhere?

And would you be interested in a PR that updates the code to use es6 Classes and any other es6 modernizations that would be appropriate?

**Comment by 3rd-Eden** [comment]
Hey,

PR are always more than welcomed. The code is currently just used internally by me for high availability purposes of a real-time system. 

I've already been working on upgrading the code to ES6, the master branch reflects the current process of this.

Currently this module only implemented the master election process. Work on implementing the Log system as described in [5.3 Log replication](https://github.com/unshiftio/liferaft/blob/master/raft.md#53-log-replication) has yet to be started. After that is done, it could be considered feature complete and 100% confirm the specification. But the current state might already be sufficient for your needs as well.

**Comment by garrensmith** [comment]
Thanks for the information. That is really helpful. Somehow I looked at the older code and didn't notice that you have done the majority of the es6 upgrades.  

This would also be used internally for a high availablity system. Most likely we will need the log consistency. We looking to combine it with [pouchdb-server](https://github.com/pouchdb/pouchdb-server) to add durability and consistency an application. I'll try and add the log replication, it will take a few weeks as I'm not working on it full time. I'll let you know once I have a basic functionality going.

Thanks for writing this. The code is great and the comments are really helpful.
