### ISSUE TITLE
.message() to an undefined "who" fails silently.

### ISSUE THREAD

**Issue by connor4312** [unshiftio/liferaft#5]
Spend an hour trying to fix something because I had written `FOLLOWERS` instead of `FOLLOWER`. Perhaps if the [nodes length](https://github.com/unshiftio/liferaft/blob/master/index.js#L561) is zero, throw an error or put one in the callback?

**Comment by 3rd-Eden** [comment]
This is definitely a bug. I think it might even make more sense to throw an error when `who` is undefined as the message cannot be send which might result in inconsistent state.
