### ISSUE TITLE
is liferaft currently safe to use in production?

### ISSUE THREAD

**Issue by wizzard0** [unshiftio/liferaft#9]
The project looks somewhat forgotten; and while the API looks nice, is it readily usable? Or shall I expect to encounter issues very soon? :)

**Comment by 3rd-Eden** [comment]
It's not forgotten, it's still loved. I just didn't have the time yet to log-replication/entries feature of it. It was something that @jcrugzz was planning to implement but never got around to implementing it. 

So as of now, only the leader and follower election process is working and should be considered production ready. Once the last pieces of functionality land it should be feature complete.

**Comment by wizzard0** [comment]
thanks, will keep watching!
